### PR TITLE
Delete arch_quick_install_software.py

### PR DESCRIPTION
**Pull request by lizongzeshunshun**
具体请参见commit详情。

### CODE REVIEW

**Comment by redapple0204** [comment]
恩，好。

**Comment by redapple0204** [comment]
另：用pyenv装了3.6，运行出错
>./python3.6 ~/my-boring-python/quickly_install_software/autodown.py 
Sorry, this platform can't run the programme.
redapple@redapple ~/.p/v/3/bin>

**Comment by lizongzeshunshun** [comment]
你是啥系统

**Comment by lizongzeshunshun** [comment]
请执行
``` python
import platform
platform.system()
``` 
结果复制给我

**Comment by redapple0204** [comment]
>redapple@redapple ~/.p/v/3/bin> ./python3.6 
Python 3.6.0 (default, Jan 20 2017, 12:17:36) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.system()
'Linux'
>>>

**Comment by lizongzeshunshun** [comment]
蛤 这就奇怪了 我看看

**Comment by lizongzeshunshun** [comment]
@redapple0204 ok

**Comment by redapple0204** [comment]
?

**Comment by lizongzeshunshun** [comment]
@redapple0204 修复了

**Comment by redapple0204** [comment]
ok,我再试试

**Comment by lizongzeshunshun** [comment]
另：安装已经包括了。请参见：wiki右侧autodown.py配置规范

**Comment by redapple0204** [comment]
额...>redapple@redapple ~/.p/v/3/bin> 
./python3.6 ~/my-boring-python/quickly_install_software/autodown.py
Welcome to use autodown.py
Version: 0.1.1 / 20170119
Start an issue on https://github.com/redapple0204/my-boring-python/issues
==============================
Now the config files:
-----------------------
-----------------------
Which do you want to run? Input the filename:
Traceback (most recent call last):
  File "/home/redapple/my-boring-python/quickly_install_software/autodown.py", line 101, in <module>
    Emain()
  File "/home/redapple/my-boring-python/quickly_install_software/autodown.py", line 85, in Emain
    jData = readFile(f"./install_config/{install}")
  File "/home/redapple/my-boring-python/quickly_install_software/autodown.py", line 13, in readFile
    with open(filepth) as f:
FileNotFoundError: [Errno 2] No such file or directory: './install_config/'
redapple@redapple ~/.p/v/3/bin>

**Comment by lizongzeshunshun** [comment]
你没有限制完整啊

install_config文件夹也要下

**Comment by redapple0204** [comment]
整个项目我都git下来了...

**Comment by lizongzeshunshun** [comment]
..i know.
你**必须**要进入autodown.py的文件夹运行，**否则**，install_config目录**应该**移动到你**执行命令的目录**

**Comment by redapple0204** [comment]
好吧.....那我得要重新弄下PATH

**Comment by lizongzeshunshun** [comment]
@redapple0204 ..py3.6还是不错的

**Comment by redapple0204** [comment]
@lizongzeshunshun 据说很容易把开发环境弄乱

**Comment by lizongzeshunshun** [comment]
@redapple0204 windows直接一个安装包上3.6.。

**Comment by redapple0204** [comment]
@lizongzeshunshun 然而3.5就不能保留了==
很多程序都不兼容3.6

**Comment by redapple0204** [comment]
另：是这样么？
>redapple@redapple ~/m/quickly_install_software> python3.6 autodown.py 
Welcome to use autodown.py
Version: 0.1.1 / 20170119
Start an issue on https://github.com/redapple0204/my-boring-python/issues
==============================
Now the config files:
-----------------------
chrome_example.json
-----------------------
Which do you want to run? Input the filename:chrome_example.json
Be careful! Some code in the config may be harmful. Check the code carefully.
------------START------------
{
    "head": {
        "name": "Chrome",
        "description": "A fast Internet browser.",
        "version": "55.0.2883.87 m"
    },
    "install": {
        "download": {
            "Windows": [
                {
                    "link": "http://baidu.com",
                    "saveName": "1"
                },
                {
                    "link": "http://baidu.com",
                    "saveName": "2"
                }
            ],
            "Linux": [
                {
                    "link": "http://baidu.com",
                    "saveName": "1"
                },
                {
                    "link": "http://baidu.com",
                    "saveName": "2"
                }
            ]
        },
        "setup": {
            "Windows": [
                "print('haha')",
                "print('example')"
            ],
            "Linux": [
                "print('haha')",
                "print('example')"
            ]
        }
    }
}

------------END--------------
Do you want to continue?[Y/n]y
redapple@redapple ~/m/quickly_install_software>

**Comment by lizongzeshunshun** [comment]
不对 Y必须是大写的（安全）

**Comment by redapple0204** [comment]
@lizongzeshunshun 
>Do you want to continue?[Y/n]Y
Downloading files...
Download finished
Setting up...
haha
example
Finished
redapple@redapple ~/m/quickly_install_software>

**Comment by lizongzeshunshun** [comment]
对了！！ 目录内应该有 1 和 2 了

**Comment by redapple0204** [comment]
@lizongzeshunshun  忘记pull了==

**Comment by lizongzeshunshun** [comment]
..

**Pull request merged**
